apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name | default "mult-app" }}
  namespace: {{ .Values.namespace | default "default" }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name | default "mult-app" }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name | default "mult-app" }}
    spec:
      containers:
      - name: {{ .Values.deployment.name | default "mult-app" }}
        image: "{{ .Values.deployment.image.repository | default "mult-app" }}:{{ .Values.deployment.image.tag | default "latest" }}"
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy | default "Never" }}
        ports:
          - containerPort: {{ .Values.service.targetPort | default 8080 }}
            name: http
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | default "64Mi" | quote }}
            cpu: {{ .Values.resources.requests.cpu | default "250m" | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | default "128Mi" | quote }}
            cpu: {{ .Values.resources.limits.cpu | default "500m" | quote }}

