namespace: "cliente-alpha" # Valor padr√£o

deployment:
  name: "mult-app"
  replicas: 1
  image:
    repository: "mult-app"
    tag: "latest"
    pullPolicy: "Never"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

configmap:
  enabled: true
  data:
    ENVIRONMENT: development
    LOG_LEVEL: debug

# Mantenha os recursos aqui para o dashboard sobrescrever
resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    cpu: "500m"
    memory: "128Mi"

resourceQuota:
  enabled: true
  limits:
    requests.cpu: "2"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 512Mi

limitRange:
  enabled: true
  default:
    cpu: 500m
    memory: 128Mi
  defaultRequest:
    cpu: 250m
    memory: 64Mi
