namespace: "cliente-alpha" 

deployment:
  name: mult-app
  replicas: 1
  image:
    repository: mult-app
    tag: latest
    pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

configmap:
  enabled: false

resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
  requests:
    cpu: "250m"
    memory: "64Mi"

resourceQuota:
  enabled: false 
  limits:
    requests.cpu: "2"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 512Mi

limitRange:
  enabled: false
