namespace: true

resourceQuota:
  enabled: true
  limits:
    requests.cpu: "2"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 512Mi

limitRange:
  enabled: true
  default:
    cpu: 500m
    memory: 128Mi
  defaultRequest:
    cpu: 250m
    memory: 64Mi
